name: Branch Social Listening Scraper

on:
  # Run daily at 9 AM UTC (adjust timezone as needed)  
  schedule:
    - cron: '0 9 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10+
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Cache Hugging Face models
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface/hub
        key: hf-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}-twitter-roberta-base-sentiment
        restore-keys: |
          hf-${{ runner.os }}-
          
    - name: Prepare Google service account file
      if: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILE != '' }}
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_FILE }}" > service_account.json
        echo "GOOGLE_SERVICE_ACCOUNT_FILE=$GITHUB_WORKSPACE/service_account.json" >> $GITHUB_ENV
        
    - name: Run Branch Social Listening Scraper
      env:
        # Google Sheets Configuration (file path set by previous step)
        GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
        
        # Slack Configuration  
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
        # Optional Configuration
        TWITTER_QUERY: ${{ secrets.TWITTER_QUERY }}
        FACEBOOK_PAGE: ${{ secrets.FACEBOOK_PAGE }}
        GOOGLE_PLAY_APP_ID: ${{ secrets.GOOGLE_PLAY_APP_ID }}
        NEGATIVE_SENTIMENT_THRESHOLD: ${{ secrets.NEGATIVE_SENTIMENT_THRESHOLD }}
        
      run: |
        python run_all.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scraper-logs
        path: branch_scraper.log
        retention-days: 30
        if-no-files-found: ignore
